In [9]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', None, 'David'],
        'Age': [25, None, 30, 22]}

df = pd.DataFrame(data)
df_cleaned = df.dropna()

print(df_cleaned)

    Name   Age
0  Alice  25.0
3  David  22.0

In [10]:
df_filled = df.fillna({'Name': 'Unknown', 'Age': df['Age'].mean()})
print(df_filled)

      Name        Age
0    Alice  25.000000
1      Bob  25.666667
2  Unknown  30.000000
3    David  22.000000

In [11]:
data = {'Name': ['Alice', 'Bob', 'Alice', 'David'],
        'Age': [25, 30, 25, 22]}

df = pd.DataFrame(data)
df_no_duplicates = df.drop_duplicates()

print(df_no_duplicates)

    Name  Age
0  Alice   25
1    Bob   30
3  David   22

In [12]:
df_replaced = df.replace({'Alice': 'Alicia'})
print(df_replaced)

     Name  Age
0  Alicia   25
1     Bob   30
2  Alicia   25
3   David   22

In [13]:
print(df.isnull())

    Name    Age
0  False  False
1  False  False
2  False  False
3  False  False

In [14]:

print(df.notnull())

   Name   Age
0  True  True
1  True  True
2  True  True
3  True  True

In [15]:
df['Age'] = df['Age'].astype('int')
print(df.dtypes)

Name    object
Age      int32
dtype: object

In [16]:
df_grouped = df.groupby('Name').mean()
print(df_grouped)

        Age
Name
Alice  25.0
Bob    30.0
David  22.0

In [17]:
import pandas as pd

# Sample DataFrame
data = {'old_name': [10, 20, 30, 40]}
df = pd.DataFrame(data)

# Rename 'old_name' to 'new_name'
df = df.rename(columns={'old_name': 'new_name'})

print(df)

   new_name
0        10
1        20
2        30
3        40

In [18]:
df = df.rename(columns={'old_name1': 'new_name1', 'old_name2': 'new_name2'})

In [19]:
df

   new_name
0        10
1        20
2        30
3        40

In [20]:
df.new_name

0    10
1    20
2    30
3    40
Name: new_name, dtype: int64

In [21]:
def fibonacci(n):
    a, b = 0, 1
    for _ in range(n):
        yield a
        a, b = b, a + b

# Using the generator
for num in fibonacci(10):
    print(num)

0
1
1
2
3
5
8
13
21
34

In [22]:
a=[1,2,3]
b=[4,5,6]
print(a*2)

[1, 2, 3, 1, 2, 3]

In [25]:
import numpy as np
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=['A','B','C','D','E'],columns=['W','X','Y','Z'])
print(df)

    W   X   Y   Z
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15
E  16  17  18  19

In [26]:
df

    W   X   Y   Z
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15
E  16  17  18  19

In [30]:
df[['W','Z']]

    W   Z
A   0   3
B   4   7
C   8  11
D  12  15
E  16  19

In [34]:
df.loc['E']

W    16
X    17
Y    18
Z    19
Name: E, dtype: int32

In [36]:
df

    W   X   Y   Z
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15
E  16  17  18  19

In [37]:
df.iloc[3,2]

14

In [39]:
df.loc[3,2]="Nan"

C:\Users\ravia\AppData\Local\Temp\ipykernel_14948\746593693.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Nan' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[3,2]="Nan"

In [40]:
df

      W     X     Y     Z    2
A   0.0   1.0   2.0   3.0  NaN
B   4.0   5.0   6.0   7.0  NaN
C   8.0   9.0  10.0  11.0  NaN
D  12.0  13.0  14.0  15.0  NaN
E  16.0  17.0  18.0  19.0  NaN
3   NaN   NaN   NaN   NaN  Nan

In [41]:
df.isnull()

       W      X      Y      Z      2
A  False  False  False  False   True
B  False  False  False  False   True
C  False  False  False  False   True
D  False  False  False  False   True
E  False  False  False  False   True
3   True   True   True   True  False

In [42]:
df.isnull().sum()

W    1
X    1
Y    1
Z    1
2    5
dtype: int64

In [44]:
df[2].value_counts()

2
Nan    1
Name: count, dtype: int64

In [45]:
df[2].unique()

array([nan, 'Nan'], dtype=object)

In [50]:
df=pd.read_csv('../Python-Learning/Marvel Movies.csv',usecols=['movie','category','year'])

In [51]:
df.head()

                     movie  category    year
0                Ant-Man     Ant-Man  2015.0
1                Ant-Man     Ant-Man  2015.0
2       Ant-Man & The Wasp   Ant-Man     NaN
3  Avengers: Age of Ultron  Avengers  2015.0
4       Avengers: End Game  Avengers  2019.0

In [53]:
df.to_csv('../Python-Learning/Marvel Moviesvtest.csv',index=False)

In [55]:
df.dropna()

                                  movie         category    year
0                             Ant-Man            Ant-Man  2015.0
1                             Ant-Man            Ant-Man  2015.0
3               Avengers: Age of Ultron         Avengers  2015.0
4                    Avengers: End Game         Avengers  2019.0
5                Avengers: Infinity War         Avengers  2018.0
6                         Black Panther    Black Panther  2018.0
8                           Black Widow           Unique  2021.0
9                       Captain America  Captain America  2011.0
10           Captain America: Civil War  Captain America  2016.0
11      Captain America: Winter Soldier  Captain America  2014.0
12                       Captain Marvel           Unique  2019.0
14    Dr Strange: Multiverse of Madness       Dr Strange  2022.0
15                             Eternals           Unique  2021.0
16              Guardians of the Galaxy        Guardians  2014.0
17            Guardians of the Galaxy 2        Guardians  2017.0
18                      Incredible Hulk           Unique  2008.0
19                             Iron Man         Iron Man  2008.0
20                           Iron Man 2         Iron Man  2010.0
21                           Iron Man 3         Iron Man  2013.0
22                            Shang-Chi           Unique  2021.0
23            Spider-Man: Far from Home       Spider-Man  2019.0
24               Spider-Man: Homecoming       Spider-Man  2017.0
25              Spider-Man: No Way Home       Spider-Man  2021.0
26                         The Avengers         Avengers  2012.0
27                     Thor: Dark World             Thor  2013.0
28                 Thor: Love & Thunder             Thor  2022.0
29                       Thor: Ragnarok             Thor  2017.0
30                                 Thor             Thor  2011.0
31    Ant-Man and the Wasp: Quantumania          Ant-Man  2023.0
32       Guardians of the Galaxy Vol. 3        Guardians  2023.0
33                          The Marvels           Unique  2023.0
34  Spider-Man: Across the Spider-Verse       Spider-Man  2023.0
35                             Deadpool         Deadpool  2016.0
36                           Deadpool 2         Deadpool  2018.0

In [59]:
df.drop_duplicates(inplace=True)

In [ ]:
df.replace()

In [60]:
df.dtypes

movie        object
category     object
year        float64
dtype: object

In [65]:
df=df.astype({'year':'int'})

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer: Error while type casting for column 'year'

In [68]:
df = df.astype({'year': 'int32', 'year': 'int64'})
print(df.dtypes)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer: Error while type casting for column 'year'

In [69]:
my_tule=(10,20,30,40)   
print(my_tule[1:3])

(20, 30)

In [70]:
my_tule[1]=25

TypeError: 'tuple' object does not support item assignment

In [71]:
my_tule=list(my_tule)
print(my_tule)

[10, 20, 30, 40]

In [72]:
my_tule[1]=25
my_tule=tuple(my_tule)

In [73]:
my_tule

(10, 25, 30, 40)

In [74]:
m_set={10,20,30,40}
print(m_set)

{40, 10, 20, 30}

In [75]:
m_set.add(10)

In [76]:
m_set.add(200)

In [77]:
m_set

{10, 20, 30, 40, 200}

In [78]:
m_set.remove(200)

In [79]:
m_set

{10, 20, 30, 40}

In [80]:
m_set.discard(200)

In [81]:
m_set

{10, 20, 30, 40}

In [82]:
m_set.pop()

40

In [83]:
m_set.pop()

10

In [84]:
a={1,2,3}
b={4,5,6}

In [85]:
a|b

{1, 2, 3, 4, 5, 6}

In [86]:
a&b

set()

In [87]:
a-b

{1, 2, 3}

In [88]:
a,b

({1, 2, 3}, {4, 5, 6})

In [89]:
a-b

{1, 2, 3}

In [90]:
a^b

{1, 2, 3, 4, 5, 6}

In [91]:
mylist=[10,20,30,40,40,20,10]

In [92]:
my_set=set(mylist)
print(my_set)

{40, 10, 20, 30}

In [93]:
# Using curly braces {}
my_dict = {"name": "Alice", "age": 25, "city": "New York"}
print(my_dict)

{'name': 'Alice', 'age': 25, 'city': 'New York'}

In [95]:
for key, value in my_dict.items():
    print(f"{key} : {value}")

name : Alice
age : 25
city : New York

In [96]:
students = {
    "Alice": {"age": 25, "grade": "A"},
    "Bob": {"age": 24, "grade": "B"}
}
print(students["Alice"]["grade"])  # Output: A

A

In [97]:
def fibonacci_iterative(n):
    fib_series = [0, 1]
    for i in range(2, n):
        fib_series.append(fib_series[i-1] + fib_series[i-2])
    return fib_series[:n]

# Example: Print first 10 Fibonacci numbers
print(fibonacci_iterative(10))

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [99]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

# Example usage
num = int(input("Enter a number: "))
if is_prime(num):
    print(f"{num} is a Prime Number")
else:
    print(f"{num} is NOT a Prime Number")

2 is a Prime Number

In [100]:
text = "Programming"
print(text[0:4])     # 'Prog' (0 to 3)
print(text[:6])      # 'Progra' (start to index 5)
print(text[4:])      # 'ramming' (index 4 to end)
print(text[::2])     # 'Pormig' (every 2nd character)
print(text[::-1])    # 'gnimmargorP' (reversed string)

Prog
Progra
ramming
Pormig
gnimmargorP

In [7]:
# write a code snippet to access the value of `'r'`.
d ={
    'a': 1,
    'b': {
        'x': 2,
        'y': 3
    },
    'c': {
        'p': {
            'r': 4,
            's': 5
        },
        'q': 6
    }
}

In [5]:
d['c']['p']['r']

4