In [798]:
import pandas as pd
!pip install matplotlib
import matplotlib.pyplot as plt

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in c:\users\ravia\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (3.10.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\ravia\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\ravia\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\ravia\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\ravia\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\ravia\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (2.2.5)
Requirement already satisfied: packaging>=20.0 in c:\users\ravia\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\ravia\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\ravia\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\ravia\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\ravia\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: C:\Users\ravia\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [799]:
data = pd.read_csv('../Problems/car data.csv')
data.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [800]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [801]:
data.shape

(301, 9)

In [802]:
data.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [803]:
data.dropna(inplace=True)

In [804]:
data['Car_Name']

0         ritz
1          sx4
2         ciaz
3      wagon r
4        swift
        ...
296       city
297       brio
298       city
299       city
300       brio
Name: Car_Name, Length: 301, dtype: object

In [805]:
data.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [806]:
import pandas as pd

# Create a sample DataFrame for data cleaning practice
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', None, 'Eva', 'Bob'],
    'Age': [25, 30, None, 22, 29, 40, 30],
    'Email': ['alice@example.com', 'bob@example', 'charlie@example.com', 'david@example.com', 'eva@example.com', None, 'bob@example'],
    'Join_Date': ['2022-01-15', '2022/02/18', '15-03-2022', '2022.04.20', None, '2022-06-10', '2022/02/18'],
    'Salary': ['50k', '55K', '60k', '50K', 'NaN', '65k', '55K']
}

df = pd.DataFrame(data)
print(df)

      Name   Age                Email   Join_Date Salary
0    Alice  25.0    alice@example.com  2022-01-15    50k
1      Bob  30.0          bob@example  2022/02/18    55K
2  Charlie   NaN  charlie@example.com  15-03-2022    60k
3    David  22.0    david@example.com  2022.04.20    50K
4     None  29.0      eva@example.com        None    NaN
5      Eva  40.0                 None  2022-06-10    65k
6      Bob  30.0          bob@example  2022/02/18    55K

In [807]:
df.head()

      Name   Age                Email   Join_Date Salary
0    Alice  25.0    alice@example.com  2022-01-15    50k
1      Bob  30.0          bob@example  2022/02/18    55K
2  Charlie   NaN  charlie@example.com  15-03-2022    60k
3    David  22.0    david@example.com  2022.04.20    50K
4     None  29.0      eva@example.com        None    NaN

In [808]:
df.isnull().sum()

Name         1
Age          1
Email        1
Join_Date    1
Salary       0
dtype: int64

In [809]:
df['Age'].fillna(df['Age'].mean(), inplace=True)

C:\Users\ravia\AppData\Local\Temp\ipykernel_6528\1698716155.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)

In [810]:
df['Age'] = df['Age'].astype(int)

In [811]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       6 non-null      object
 1   Age        7 non-null      int64
 2   Email      6 non-null      object
 3   Join_Date  6 non-null      object
 4   Salary     7 non-null      object
dtypes: int64(1), object(4)
memory usage: 412.0+ bytes

In [812]:
df['Join_Date']

0    2022-01-15
1    2022/02/18
2    15-03-2022
3    2022.04.20
4          None
5    2022-06-10
6    2022/02/18
Name: Join_Date, dtype: object

In [813]:
df['Join_Date']

0    2022-01-15
1    2022/02/18
2    15-03-2022
3    2022.04.20
4          None
5    2022-06-10
6    2022/02/18
Name: Join_Date, dtype: object

In [814]:
df

      Name  Age                Email   Join_Date Salary
0    Alice   25    alice@example.com  2022-01-15    50k
1      Bob   30          bob@example  2022/02/18    55K
2  Charlie   29  charlie@example.com  15-03-2022    60k
3    David   22    david@example.com  2022.04.20    50K
4     None   29      eva@example.com        None    NaN
5      Eva   40                 None  2022-06-10    65k
6      Bob   30          bob@example  2022/02/18    55K

In [815]:
df.dropna(subset=['Email'], inplace=True)
df.dropna(subset=['Join_Date'], inplace=True)

In [816]:
df

      Name  Age                Email   Join_Date Salary
0    Alice   25    alice@example.com  2022-01-15    50k
1      Bob   30          bob@example  2022/02/18    55K
2  Charlie   29  charlie@example.com  15-03-2022    60k
3    David   22    david@example.com  2022.04.20    50K
6      Bob   30          bob@example  2022/02/18    55K

In [817]:
df['Join_Date'] = df['Join_Date'].str.replace('/', '-').str.replace('.', '-')
df['Join_Date'] = pd.to_datetime(df['Join_Date'], errors='coerce')
# df['Join_Date']=pd.to_datetime(df['Join_Date'])

In [818]:
df

      Name  Age                Email  Join_Date Salary
0    Alice   25    alice@example.com 2022-01-15    50k
1      Bob   30          bob@example 2022-02-18    55K
2  Charlie   29  charlie@example.com        NaT    60k
3    David   22    david@example.com 2022-04-20    50K
6      Bob   30          bob@example 2022-02-18    55K

In [819]:
import pandas as pd

# Create the DataFrame
data = {
    'First_name': ['Bhoomi', 'Nisha', 'Abhishek', 'Neha', 'Neha'],
    'last_name': ['Devnani', 'Sharma', 'Tiwari', 'Jain', 'Jain'],
    'Gender': ['female', 'female', 'male', None, None],
    'Salary': [20000.0, None, 10000.0, None, None],
    'Department': ['cse', 'cse', 'bca', 'bca', 'bca'],
    'working hours': [10, 8, 18, 11, 11],
    'Doj': ['12-01-2023', '13-02-2023', '14-01-2023', '12-01-2023', '12-01-2023']
}

df = pd.DataFrame(data)
print(df)

  First_name last_name  Gender   Salary Department  working hours         Doj
0     Bhoomi   Devnani  female  20000.0        cse             10  12-01-2023
1      Nisha    Sharma  female      NaN        cse              8  13-02-2023
2   Abhishek    Tiwari    male  10000.0        bca             18  14-01-2023
3       Neha      Jain    None      NaN        bca             11  12-01-2023
4       Neha      Jain    None      NaN        bca             11  12-01-2023

In [820]:
df

  First_name last_name  Gender   Salary Department  working hours         Doj
0     Bhoomi   Devnani  female  20000.0        cse             10  12-01-2023
1      Nisha    Sharma  female      NaN        cse              8  13-02-2023
2   Abhishek    Tiwari    male  10000.0        bca             18  14-01-2023
3       Neha      Jain    None      NaN        bca             11  12-01-2023
4       Neha      Jain    None      NaN        bca             11  12-01-2023

In [821]:
df['Gender'].fillna(df['Gender'].mode()[0],inplace=True)

C:\Users\ravia\AppData\Local\Temp\ipykernel_6528\3554240144.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna(df['Gender'].mode()[0],inplace=True)

In [822]:
df['Salary'].fillna(df['Salary'].mean(),inplace=True)
df['Salary'] = df['Salary'].astype(int)

C:\Users\ravia\AppData\Local\Temp\ipykernel_6528\3204062986.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(),inplace=True)

In [823]:
df

  First_name last_name  Gender  Salary Department  working hours         Doj
0     Bhoomi   Devnani  female   20000        cse             10  12-01-2023
1      Nisha    Sharma  female   15000        cse              8  13-02-2023
2   Abhishek    Tiwari    male   10000        bca             18  14-01-2023
3       Neha      Jain  female   15000        bca             11  12-01-2023
4       Neha      Jain  female   15000        bca             11  12-01-2023

In [824]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   First_name     5 non-null      object
 1   last_name      5 non-null      object
 2   Gender         5 non-null      object
 3   Salary         5 non-null      int64
 4   Department     5 non-null      object
 5   working hours  5 non-null      int64
 6   Doj            5 non-null      object
dtypes: int64(2), object(5)
memory usage: 412.0+ bytes

In [825]:
df['Doj'] = pd.to_datetime(df['Doj'], format='%d-%m-%Y')

In [826]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   First_name     5 non-null      object
 1   last_name      5 non-null      object
 2   Gender         5 non-null      object
 3   Salary         5 non-null      int64
 4   Department     5 non-null      object
 5   working hours  5 non-null      int64
 6   Doj            5 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(4)
memory usage: 412.0+ bytes

In [827]:
df.isnull().sum()

First_name       0
last_name        0
Gender           0
Salary           0
Department       0
working hours    0
Doj              0
dtype: int64

In [828]:
df

  First_name last_name  Gender  Salary Department  working hours        Doj
0     Bhoomi   Devnani  female   20000        cse             10 2023-01-12
1      Nisha    Sharma  female   15000        cse              8 2023-02-13
2   Abhishek    Tiwari    male   10000        bca             18 2023-01-14
3       Neha      Jain  female   15000        bca             11 2023-01-12
4       Neha      Jain  female   15000        bca             11 2023-01-12

In [829]:
df.drop_duplicates(inplace=True)

In [830]:
df

  First_name last_name  Gender  Salary Department  working hours        Doj
0     Bhoomi   Devnani  female   20000        cse             10 2023-01-12
1      Nisha    Sharma  female   15000        cse              8 2023-02-13
2   Abhishek    Tiwari    male   10000        bca             18 2023-01-14
3       Neha      Jain  female   15000        bca             11 2023-01-12

In [831]:
import pandas as pd

data = {
    'Employee_ID': [101, 102, 103, 104, 105],
    'Name': ['Arjun', 'Meera', 'Sahil', 'Diya', 'Kiran'],
    'Join_Date': ['2023-01-10', '12/02/2023', '15-03-2023', None, '2023.04.25'],
    'Department': ['HR', 'Finance', None, 'HR', 'finance'],
    'Salary': [50000, None, 55000, 52000, 54000],
    'Gender': ['Male', 'Female', 'M', 'F', None]
}

df = pd.DataFrame(data)
print(df)

   Employee_ID   Name   Join_Date Department   Salary  Gender
0          101  Arjun  2023-01-10         HR  50000.0    Male
1          102  Meera  12/02/2023    Finance      NaN  Female
2          103  Sahil  15-03-2023       None  55000.0       M
3          104   Diya        None         HR  52000.0       F
4          105  Kiran  2023.04.25    finance  54000.0    None

In [832]:
df

   Employee_ID   Name   Join_Date Department   Salary  Gender
0          101  Arjun  2023-01-10         HR  50000.0    Male
1          102  Meera  12/02/2023    Finance      NaN  Female
2          103  Sahil  15-03-2023       None  55000.0       M
3          104   Diya        None         HR  52000.0       F
4          105  Kiran  2023.04.25    finance  54000.0    None

In [833]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  5 non-null      int64
 1   Name         5 non-null      object
 2   Join_Date    4 non-null      object
 3   Department   4 non-null      object
 4   Salary       4 non-null      float64
 5   Gender       4 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 372.0+ bytes

In [834]:
df.isnull().sum()

Employee_ID    0
Name           0
Join_Date      1
Department     1
Salary         1
Gender         1
dtype: int64

In [835]:
df['Salary'].fillna(df['Salary'].mean(),inplace=True)
df['Salary'] = df['Salary'].astype(int)

C:\Users\ravia\AppData\Local\Temp\ipykernel_6528\3204062986.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(),inplace=True)

In [836]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  5 non-null      int64
 1   Name         5 non-null      object
 2   Join_Date    4 non-null      object
 3   Department   4 non-null      object
 4   Salary       5 non-null      int64
 5   Gender       4 non-null      object
dtypes: int64(2), object(4)
memory usage: 372.0+ bytes

In [837]:
df['Gender']

0      Male
1    Female
2         M
3         F
4      None
Name: Gender, dtype: object

In [838]:
df['Gender'].replace({'Male':'M','Female':'F'},inplace=True)

In [839]:
df['Gender'].fillna(df['Gender'].mode()[0],inplace=True)

In [840]:
df['Gender']=df['Gender'].astype(str)

In [841]:
df['Department'].fillna(df['Department'].mode()[0],inplace=True)

C:\Users\ravia\AppData\Local\Temp\ipykernel_6528\4244018208.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Department'].fillna(df['Department'].mode()[0],inplace=True)

In [842]:
df

   Employee_ID   Name   Join_Date Department  Salary Gender
0          101  Arjun  2023-01-10         HR   50000      M
1          102  Meera  12/02/2023    Finance   52750      F
2          103  Sahil  15-03-2023         HR   55000      M
3          104   Diya        None         HR   52000      F
4          105  Kiran  2023.04.25    finance   54000      F

In [843]:
df['Join_Date'] = df['Join_Date'].str.replace('/', '-').str.replace('.', '-')
# df['Join_Date'] = pd.to_datetime(df['Join_Date'],dayfirst=True, errors='coerce')

In [844]:
df

   Employee_ID   Name   Join_Date Department  Salary Gender
0          101  Arjun  2023-01-10         HR   50000      M
1          102  Meera  12-02-2023    Finance   52750      F
2          103  Sahil  15-03-2023         HR   55000      M
3          104   Diya        None         HR   52000      F
4          105  Kiran  2023-04-25    finance   54000      F

In [845]:
# df['Join_Date'] = pd.to_datetime(df['Join_Date'], errors='coerce')

In [846]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  5 non-null      int64
 1   Name         5 non-null      object
 2   Join_Date    4 non-null      object
 3   Department   5 non-null      object
 4   Salary       5 non-null      int64
 5   Gender       5 non-null      object
dtypes: int64(2), object(4)
memory usage: 372.0+ bytes

In [847]:
# from datetime import datetime
# df['Join_Date'].fillna(datetime.now(),inplace=True)

In [848]:
df

   Employee_ID   Name   Join_Date Department  Salary Gender
0          101  Arjun  2023-01-10         HR   50000      M
1          102  Meera  12-02-2023    Finance   52750      F
2          103  Sahil  15-03-2023         HR   55000      M
3          104   Diya        None         HR   52000      F
4          105  Kiran  2023-04-25    finance   54000      F

In [849]:
df['Department'] = df['Department'].str.title()

In [850]:
df

   Employee_ID   Name   Join_Date Department  Salary Gender
0          101  Arjun  2023-01-10         Hr   50000      M
1          102  Meera  12-02-2023    Finance   52750      F
2          103  Sahil  15-03-2023         Hr   55000      M
3          104   Diya        None         Hr   52000      F
4          105  Kiran  2023-04-25    Finance   54000      F

In [851]:
# df['Join_Date'] = pd.to_datetime(df['Join_Date'], errors='coerce')

In [852]:
from datetime import datetime
df['Join_Date'].fillna(datetime.today().date(), inplace=True)

C:\Users\ravia\AppData\Local\Temp\ipykernel_6528\4294310564.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Join_Date'].fillna(datetime.today().date(), inplace=True)

In [853]:
df

   Employee_ID   Name   Join_Date Department  Salary Gender
0          101  Arjun  2023-01-10         Hr   50000      M
1          102  Meera  12-02-2023    Finance   52750      F
2          103  Sahil  15-03-2023         Hr   55000      M
3          104   Diya  2025-05-08         Hr   52000      F
4          105  Kiran  2023-04-25    Finance   54000      F

In [854]:
# df['Join_Date'] = pd.to_datetime(df['Join_Date'], errors='coerce')
# df['Join_Date'] = df['Join_Date'].dt.strftime('%Y-%m-%d')

In [855]:
df

   Employee_ID   Name   Join_Date Department  Salary Gender
0          101  Arjun  2023-01-10         Hr   50000      M
1          102  Meera  12-02-2023    Finance   52750      F
2          103  Sahil  15-03-2023         Hr   55000      M
3          104   Diya  2025-05-08         Hr   52000      F
4          105  Kiran  2023-04-25    Finance   54000      F

In [858]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'],format='mixed',dayfirst=True, errors='coerce')

In [857]:
df

   Employee_ID   Name  Join_Date Department  Salary Gender
0          101  Arjun 2023-01-10         Hr   50000      M
1          102  Meera 2023-02-12    Finance   52750      F
2          103  Sahil 2023-03-15         Hr   55000      M
3          104   Diya 2025-05-08         Hr   52000      F
4          105  Kiran 2023-04-25    Finance   54000      F

In [863]:
import pandas as pd

data = {
    'Full_Name': ['Arjun Kumar', 'Meera Singh', 'Sahil Reddy', 'Diya Patel', 'Kiran Das'],
    'Email': ['arjun.k@example.com', 'meera.s@example.com', 'sahil.r@example.com', 'diya.p@example.com', 'kiran.d@example.com']
}

df = pd.DataFrame(data)
print(df)

     Full_Name                Email
0  Arjun Kumar  arjun.k@example.com
1  Meera Singh  meera.s@example.com
2  Sahil Reddy  sahil.r@example.com
3   Diya Patel   diya.p@example.com
4    Kiran Das  kiran.d@example.com

In [865]:
df[['First_Name','Last_Name']]=df['Full_Name'].str.split(' ',expand=True)

In [867]:
df.drop(columns='Full_Name',axis=1,inplace=True)

In [868]:
df

                 Email First_Name Last_Name
0  arjun.k@example.com      Arjun     Kumar
1  meera.s@example.com      Meera     Singh
2  sahil.r@example.com      Sahil     Reddy
3   diya.p@example.com       Diya     Patel
4  kiran.d@example.com      Kiran       Das

In [869]:
df['Email']=df['Email'].str.replace('@example.com','@gmail.com')

In [870]:
df

               Email First_Name Last_Name
0  arjun.k@gmail.com      Arjun     Kumar
1  meera.s@gmail.com      Meera     Singh
2  sahil.r@gmail.com      Sahil     Reddy
3   diya.p@gmail.com       Diya     Patel
4  kiran.d@gmail.com      Kiran       Das