Learning

In [1]:
name = str(input("Enter String").lower())
vowels = ['a', 'e', 'i', 'o', 'u']
count = 0
for i in name:
    if i in vowels:
        count += 1
print("Number of vowels in the string is: ", count)

Number of vowels in the string is:  3

## Nested Loops

In [2]:
for i in range(1,6):
    print(i*"* ")

*
* *
* * *
* * * *
* * * * *

In [3]:
for i in range(1,6):
    for j in range(0,i):
        print("*", end=" ")
    print("")

*
* *
* * *
* * * *
* * * * *

In [4]:
for i in range(1,6,+1):
    print(" "*(6-i), end="")
    for j in range(1,i+1):
        print(j, end=" ")

    print("")

     1
    1 2
   1 2 3
  1 2 3 4
 1 2 3 4 5

In [5]:
number = 1
for i in range(1,6,+1):
    for j in range(i):
        print(number, end=" ")
        number += 1
    print("")

1
2 3
4 5 6
7 8 9 10
11 12 13 14 15

In [1]:
# fibonaki serie
number = int(input("Enter the number of terms: "))
a, b = 0, 1
print("Fibonacci sequence:")
for i in range(number):
    print(a, end=" ")
    a, b = b, a + b

print("")

Fibonacci sequence:
0 1 1 2 3 5 8 13 21 34

In [7]:
for vowel in reversed(vowels):
    print(vowel)

u
o
i
e
a

In [3]:
import pandas as pd
data = {
    "x":[1,2,3,4,5],
    "y":[300,400,500,600,700]
}
data=pd.DataFrame(data)
data

   x    y
0  1  300
1  2  400
2  3  500
3  4  600
4  5  700

In [4]:
import pandas as pd
df = pd.DataFrame(data)
df['new']=df['y'].apply(lambda x: x*2)
df

   x    y   new
0  1  300   600
1  2  400   800
2  3  500  1000
3  4  600  1200
4  5  700  1400

In [12]:
exam_data={
    "name":["ravi","Mitul","Abhi","sahil","udit"],
    "marks":[90,95,15,45,60]
}

df=pd.DataFrame(exam_data)
df

    name  marks
0   ravi     90
1  Mitul     95
2   Abhi     15
3  sahil     45
4   udit     60

In [13]:
df['result']= df['marks'].apply(lambda x:"A" if x>=90 else ("B" if x>=50 else "C"))

In [7]:
df

    name  marks result
0   ravi     90      A
1  Mitul     95      A
2   Abhi     15      C
3  sahil     45      C
4   udit     60      B

In [8]:
data = pd.DataFrame({
    "patient_id":[1,2,3,4,5,6,7,8],
    "name":["a","b","c","d","e","f","g","h"],
    "weight":[20,78,52,96,53,45,76,61],
    "height":[1.7,2,2.1,1.6,1.2,1,1.8,2.2]
})

In [9]:
data

   patient_id name  weight  height
0           1    a      20     1.7
1           2    b      78     2.0
2           3    c      52     2.1
3           4    d      96     1.6
4           5    e      53     1.2
5           6    f      45     1.0
6           7    g      76     1.8
7           8    h      61     2.2

In [10]:
#BMI Calculcation
def bmi_cal(row):
    return row['weight']/(row['height']**2)

In [11]:
data["BMI"]=data.apply(bmi_cal,axis=1)
data

   patient_id name  weight  height        BMI
0           1    a      20     1.7   6.920415
1           2    b      78     2.0  19.500000
2           3    c      52     2.1  11.791383
3           4    d      96     1.6  37.500000
4           5    e      53     1.2  36.805556
5           6    f      45     1.0  45.000000
6           7    g      76     1.8  23.456790
7           8    h      61     2.2  12.603306

In [14]:
import pandas as pd

# Sample data
data = {
    'Order ID': [101, 102, 103, 104, 105, 106, 102, 104],  # duplicate Order IDs
    'Category': ['Electronics', 'Clothing', 'Electronics', 'Books', 'Books', 'Clothing', 'Clothing', 'Books'],
    'Amount': [250, 80, 300, 20, 25, 75, 80, 20],
    'Quantity': [1, 2, 1, 3, 2, 1, 2, 3]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
   Order ID     Category  Amount  Quantity
0       101  Electronics     250         1
1       102     Clothing      80         2
2       103  Electronics     300         1
3       104        Books      20         3
4       105        Books      25         2
5       106     Clothing      75         1
6       102     Clothing      80         2
7       104        Books      20         3

In [17]:
df_unique_orders = df.drop_duplicates(subset='Order ID', keep='first')
df_unique_orders

   Order ID     Category  Amount  Quantity
0       101  Electronics     250         1
1       102     Clothing      80         2
2       103  Electronics     300         1
3       104        Books      20         3
4       105        Books      25         2
5       106     Clothing      75         1

In [19]:
category_summary = df.groupby('Category').agg({
    'Amount': 'sum',
    'Quantity': 'sum'
}).reset_index()
category_summary

      Category  Amount  Quantity
0        Books      65         8
1     Clothing     235         5
2  Electronics     550         2

----

In [20]:
import pandas as pd

# Sample employee data
data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan'],
    'Base Salary': [60000, 75000, 50000, 82000, 90000],
    'Performance Rating': [4.5, 3.8, 4.9, 3.2, 4.0]
}

# Create DataFrame
df = pd.DataFrame(data)

# Bonus calculation logic (example: 10% to 20% based on rating)
def calculate_bonus(salary, rating):
    if rating >= 4.5:
        return salary * 0.20
    elif rating >= 4.0:
        return salary * 0.15
    elif rating >= 3.5:
        return salary * 0.10
    else:
        return salary * 0.05

# Apply bonus calculation
df['Bonus'] = df.apply(lambda row: calculate_bonus(row['Base Salary'], row['Performance Rating']), axis=1)

# Total salary after bonus
df['Total Salary'] = df['Base Salary'] + df['Bonus']

print(df)

  Employee  Base Salary  Performance Rating    Bonus  Total Salary
0    Alice        60000                 4.5  12000.0       72000.0
1      Bob        75000                 3.8   7500.0       82500.0
2  Charlie        50000                 4.9  10000.0       60000.0
3    Diana        82000                 3.2   4100.0       86100.0
4    Ethan        90000                 4.0  13500.0      103500.0

-----

In [2]:
import pandas as pd

# Sample data
data = {
    'Order ID': [101, 102, 103, 104, 105, 106, 102, 104],  # duplicate Order IDs
    'Category': ['Electronics', 'Clothing', 'Electronics', 'Books', 'Books', 'Clothing', 'Clothing', 'Books'],
    'Amount': [250, 80, 300, 20, 25, 75, 80, 20],
    'Quantity': [1, 2, 1, 3, 2, 1, 2, 3]
}

df = pd.DataFrame(data)

# Aggregate by category
category_summary = df.groupby('Category').agg({
    'Amount': 'sum',
    'Quantity': 'sum'
}).reset_index()

# Sort in descending order of total Amount
category_summary = category_summary.sort_values(by='Amount', ascending=False)

print("Aggregated and Sorted by Amount (Descending):")
category_summary=pd.DataFrame(category_summary)
print(category_summary)

Aggregated and Sorted by Amount (Descending):
      Category  Amount  Quantity
2  Electronics     550         2
1     Clothing     235         5
0        Books      65         8

In [4]:
# finding duplicates from the list
list1 = [1,2,3,4,5,6,7,8,9,10,10,9]
duplicates=list(set([x for x in list1 if list1.count(x)>1]))
duplicates

[9, 10]

In [5]:
x = int(input("Enter a number: "))
list1 = [10, 20, 30, 40]

for item in list1:
    if item == x:
        print(f"{x} found")
        break

30 found

-----

## LAmbda Function

In [1]:
# Return length of string
String_length=lambda x: len(x)
print(String_length("Hello World"))

11

### Map Function

In [8]:
list1=[1,2,3,4,5]
squares=list(map(lambda x: x**2,list1))
squares

[1, 4, 9, 16, 25]

### Filter Function

In [9]:
#filer even numbers from list
list1=[1,2,3,4,5,6,7,8,9,10]
even=list(filter(lambda x: x%2==0,list1))
even

[2, 4, 6, 8, 10]

In [10]:
#filer even numbers from list
list1=[1,2,3,4,5,6,7,8,9,10]
even=list(filter(lambda x: x%2!=0,list1))
even

[1, 3, 5, 7, 9]

### sorted

In [14]:
#sort the list of string based on length
list1=["app","bna","kiwi","mago"]
sorted_list=sorted(list1,key=lambda x: len(x))  
sorted_list

['app', 'bna', 'kiwi', 'mago']

In [15]:
#sort a list of dictionary based on a specific key
list1=[{"name":"ravi","age":20},{"name":"mitul","age":25},{"name":"abhi","age":22}]
sorted_list=sorted(list1,key=lambda x: x["age"])  
sorted_list

[{'name': 'ravi', 'age': 20},
 {'name': 'abhi', 'age': 22},
 {'name': 'mitul', 'age': 25}]

In [18]:
#finding maximum value from the dictionary
list1=[{"name":"ravi","age":20},{"name":"mitul","age":25},{"name":"abhi","age":22}]
max_value=max(list1,key=lambda x: x["age"])  
max_value

{'name': 'mitul', 'age': 25}

In [20]:
#grouping the list of string based on first character
words=["apple","banana","kiwi","mango"]
from itertools import groupby
grouped_words=groupby(sorted(words),key=lambda x: x[0])  
for key, group in grouped_words:
    print(key, list(group))

a ['apple']
b ['banana']
k ['kiwi']
m ['mango']

----

### reduce

In [44]:
from functools import reduce
# Sample list
numbers = [1, 2, 3, 4, 5]
# Using reduce to calculate the sum of the list
reduce(lambda x, y: x + y, numbers)

# sum(numbers)

15

In [26]:
reduce(lambda x,y : x if x>y else y, numbers)

5

In [27]:
reduce(lambda x,y : x if x<y else y, numbers)

1

In [23]:
data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan'],
    'Base Salary': [60000, 75000, 50000, 82000, 90000],
    'Performance Rating': [4.5, 3.8, 4.9, 3.2, 4.0]
}

reduce(lambda x, y: x + y, data['Base Salary'])

357000

In [28]:
l=[1,2,3,4,5]
{x: x**2 for x in l if x%2==0}

{2: 4, 4: 16}

In [29]:
l=[1,2,3,4,5]
{x: x**2 for x in l}

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

---- 


### Group By

In [26]:
df = pd.DataFrame({'Animal': ['Falcon', 'Falcon',
'Parrot', 'Parrot'],
'Max Speed': [380., 370., 24., 26.]})
df

df.groupby(['Animal']).mean()

df.groupby(['Animal']).sum()

df.groupby(['Animal']).min()

df.groupby(['Animal']).max()


print(df.groupby(['Animal']).mean())

        Max Speed
Animal
Falcon      375.0
Parrot       25.0

In [11]:
arrays = [['Falcon', 'Falcon', 'Parrot', 'Parrot'],
          ['Captive', 'Wild', 'Captive', 'Wild']]

index = pd.MultiIndex.from_arrays(arrays, names=('Animal', 'Type'))
df = pd.DataFrame({'Max Speed': [390., 350., 30., 20.]},
                  index=index)
df

                Max Speed
Animal Type
Falcon Captive      390.0
       Wild         350.0
Parrot Captive       30.0
       Wild          20.0

In [12]:
l = [[1, 2, 3], [1, None, 4], [2, 1, 3], [1, 2, 2]]
l

[[1, 2, 3], [1, None, 4], [2, 1, 3], [1, 2, 2]]

In [13]:
df = pd.DataFrame(l, columns=["a", "b", "c"])

In [14]:
df.groupby(by=["b"]).sum()

     a  c
b
1.0  2  3
2.0  2  5

In [16]:
df = pd.DataFrame({'Animal': ['Falcon', 'Falcon',
                              'Parrot', 'Parrot'],
                   'Max Speed': [380., 370., 24., 26.]})

df.groupby("Animal", group_keys=True)[['Max Speed']].apply(lambda x: x)

          Max Speed
Animal
Falcon 0      380.0
       1      370.0
Parrot 2       24.0
       3       26.0

In [20]:
df.groupby("Animal", group_keys=True)[['Max Speed']].max()

        Max Speed
Animal
Falcon      380.0
Parrot       26.0

In [23]:
df.groupby("Animal", group_keys=False)[['Max Speed']].apply(lambda x: x)

   Max Speed
0      380.0
1      370.0
2       24.0
3       26.0

In [33]:
import pandas as pd

# Sample DataFrame
data = {
    'Department': ['Sales', 'Sales', 'HR', 'HR', 'IT', 'IT'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Salary': [50000, 55000, 60000, 62000, 70000, 72000]
}

df = pd.DataFrame(data)

# Group by department and calculate average salary
df.groupby('Department')['Salary'].mean()

Department
HR       61000.0
IT       71000.0
Sales    52500.0
Name: Salary, dtype: float64

In [34]:
df['Region'] = ['East', 'West', 'East', 'West', 'East', 'West']

In [35]:
# Group by Department and Region
df.groupby(['Department', 'Region'])['Salary'].mean()

Department  Region
HR          East      60000.0
            West      62000.0
IT          East      70000.0
            West      72000.0
Sales       East      50000.0
            West      55000.0
Name: Salary, dtype: float64

In [37]:
# Transform: Assign each row the average salary of their department
df['Dept_Avg_Salary'] = df.groupby('Department')['Salary'].transform('mean')
df

  Department Employee  Salary Region  Dept_Avg_Salary
0      Sales    Alice   50000   East          52500.0
1      Sales      Bob   55000   West          52500.0
2         HR  Charlie   60000   East          61000.0
3         HR    David   62000   West          61000.0
4         IT      Eve   70000   East          71000.0
5         IT    Frank   72000   West          71000.0

## Sorted_Values

In [2]:
import pandas as pd
# Sample DataFrame
data = {'col1': [3, 1, 4, 2], 'col2': ['c', 'a', 'd', 'b']}
df = pd.DataFrame(data)

# Sort by 'col1' in ascending order
df_sorted_col1 = df.sort_values(by='col1')

# Sort by 'col2' in descending order
df_sorted_col2_desc = df.sort_values(by='col2', ascending=False)

# Sort by multiple columns
df_sorted_multi = df.sort_values(by=['col1', 'col2'])
df_sorted_multi

   col1 col2
1     1    a
3     2    b
0     3    c
2     4    d

## Sorted

In [4]:
# Sample list
list1 = [3, 1, 4, 2]

# Sort the list in ascending order
sorted_list_asc = sorted(list1)

# Sort the list in descending order
sorted_list_desc = sorted(list1, reverse=True)

# Sort a list of strings by length
list2 = ['apple', 'banana', 'kiwi']
sorted_list_len = sorted(list2, key=len)
sorted_list_len

['kiwi', 'apple', 'banana']

In [2]:
# Remove duplicates from the list while preserving order (without built-in methods)
list1 = [1,2,3,4,5,6,7,8,9,10,10,9]

for i in list1:
    if list1.count(i) > 1:
        while list1.count(i) > 1:
            list1.remove(i)
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 10, 9]

In [3]:
list1

[1, 2, 3, 4, 5, 6, 7, 8, 10, 9]

In [5]:
list1[::2]

[1, 3, 5, 7, 10]