Learning

In [1]:
name = str(input("Enter String").lower())
vowels = ['a', 'e', 'i', 'o', 'u']
count = 0
for i in name:
    if i in vowels:
        count += 1
print("Number of vowels in the string is: ", count)

Number of vowels in the string is:  3

## Nested Loops

In [2]:
for i in range(1,6):
    print(i*"* ")

*
* *
* * *
* * * *
* * * * *

In [3]:
for i in range(1,6):
    for j in range(0,i):
        print("*", end=" ")
    print("")

*
* *
* * *
* * * *
* * * * *

In [4]:
for i in range(1,6,+1):
    print(" "*(6-i), end="")
    for j in range(1,i+1):
        print(j, end=" ")

    print("")

     1
    1 2
   1 2 3
  1 2 3 4
 1 2 3 4 5

In [5]:
number = 1
for i in range(1,6,+1):
    for j in range(i):
        print(number, end=" ")
        number += 1
    print("")

1
2 3
4 5 6
7 8 9 10
11 12 13 14 15

In [6]:
# fibonaki serie
number = int(input("Enter the number of terms: "))
a, b = 0, 1
print("Fibonacci sequence:")
for i in range(number):
    print(a, end=" ")
    a, b = b, a + b

print("")

Fibonacci sequence:
0 1 1 2 3

In [7]:
for vowel in reversed(vowels):
    print(vowel)

u
o
i
e
a

In [3]:
import pandas as pd
data = {
    "x":[1,2,3,4,5],
    "y":[300,400,500,600,700]
}
data=pd.DataFrame(data)
data

   x    y
0  1  300
1  2  400
2  3  500
3  4  600
4  5  700

In [4]:
import pandas as pd
df = pd.DataFrame(data)
df['new']=df['y'].apply(lambda x: x*2)
df

   x    y   new
0  1  300   600
1  2  400   800
2  3  500  1000
3  4  600  1200
4  5  700  1400

In [12]:
exam_data={
    "name":["ravi","Mitul","Abhi","sahil","udit"],
    "marks":[90,95,15,45,60]
}

df=pd.DataFrame(exam_data)
df

    name  marks
0   ravi     90
1  Mitul     95
2   Abhi     15
3  sahil     45
4   udit     60

In [13]:
df['result']= df['marks'].apply(lambda x:"A" if x>=90 else ("B" if x>=50 else "C"))

In [7]:
df

    name  marks result
0   ravi     90      A
1  Mitul     95      A
2   Abhi     15      C
3  sahil     45      C
4   udit     60      B

In [8]:
data = pd.DataFrame({
    "patient_id":[1,2,3,4,5,6,7,8],
    "name":["a","b","c","d","e","f","g","h"],
    "weight":[20,78,52,96,53,45,76,61],
    "height":[1.7,2,2.1,1.6,1.2,1,1.8,2.2]
})

In [9]:
data

   patient_id name  weight  height
0           1    a      20     1.7
1           2    b      78     2.0
2           3    c      52     2.1
3           4    d      96     1.6
4           5    e      53     1.2
5           6    f      45     1.0
6           7    g      76     1.8
7           8    h      61     2.2

In [10]:
#BMI Calculcation
def bmi_cal(row):
    return row['weight']/(row['height']**2)

In [11]:
data["BMI"]=data.apply(bmi_cal,axis=1)
data

   patient_id name  weight  height        BMI
0           1    a      20     1.7   6.920415
1           2    b      78     2.0  19.500000
2           3    c      52     2.1  11.791383
3           4    d      96     1.6  37.500000
4           5    e      53     1.2  36.805556
5           6    f      45     1.0  45.000000
6           7    g      76     1.8  23.456790
7           8    h      61     2.2  12.603306

In [14]:
import pandas as pd

# Sample data
data = {
    'Order ID': [101, 102, 103, 104, 105, 106, 102, 104],  # duplicate Order IDs
    'Category': ['Electronics', 'Clothing', 'Electronics', 'Books', 'Books', 'Clothing', 'Clothing', 'Books'],
    'Amount': [250, 80, 300, 20, 25, 75, 80, 20],
    'Quantity': [1, 2, 1, 3, 2, 1, 2, 3]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
   Order ID     Category  Amount  Quantity
0       101  Electronics     250         1
1       102     Clothing      80         2
2       103  Electronics     300         1
3       104        Books      20         3
4       105        Books      25         2
5       106     Clothing      75         1
6       102     Clothing      80         2
7       104        Books      20         3

In [17]:
df_unique_orders = df.drop_duplicates(subset='Order ID', keep='first')
df_unique_orders

   Order ID     Category  Amount  Quantity
0       101  Electronics     250         1
1       102     Clothing      80         2
2       103  Electronics     300         1
3       104        Books      20         3
4       105        Books      25         2
5       106     Clothing      75         1

In [19]:
category_summary = df.groupby('Category').agg({
    'Amount': 'sum',
    'Quantity': 'sum'
}).reset_index()
category_summary

      Category  Amount  Quantity
0        Books      65         8
1     Clothing     235         5
2  Electronics     550         2

----

In [20]:
import pandas as pd

# Sample employee data
data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan'],
    'Base Salary': [60000, 75000, 50000, 82000, 90000],
    'Performance Rating': [4.5, 3.8, 4.9, 3.2, 4.0]
}

# Create DataFrame
df = pd.DataFrame(data)

# Bonus calculation logic (example: 10% to 20% based on rating)
def calculate_bonus(salary, rating):
    if rating >= 4.5:
        return salary * 0.20
    elif rating >= 4.0:
        return salary * 0.15
    elif rating >= 3.5:
        return salary * 0.10
    else:
        return salary * 0.05

# Apply bonus calculation
df['Bonus'] = df.apply(lambda row: calculate_bonus(row['Base Salary'], row['Performance Rating']), axis=1)

# Total salary after bonus
df['Total Salary'] = df['Base Salary'] + df['Bonus']

print(df)

  Employee  Base Salary  Performance Rating    Bonus  Total Salary
0    Alice        60000                 4.5  12000.0       72000.0
1      Bob        75000                 3.8   7500.0       82500.0
2  Charlie        50000                 4.9  10000.0       60000.0
3    Diana        82000                 3.2   4100.0       86100.0
4    Ethan        90000                 4.0  13500.0      103500.0

-----

In [24]:
import pandas as pd

# Sample data
data = {
    'Order ID': [101, 102, 103, 104, 105, 106, 102, 104],  # duplicate Order IDs
    'Category': ['Electronics', 'Clothing', 'Electronics', 'Books', 'Books', 'Clothing', 'Clothing', 'Books'],
    'Amount': [250, 80, 300, 20, 25, 75, 80, 20],
    'Quantity': [1, 2, 1, 3, 2, 1, 2, 3]
}

df = pd.DataFrame(data)

# Aggregate by category
category_summary = df.groupby('Category').agg({
    'Amount': 'sum',
    'Quantity': 'sum'
}).reset_index()

# Sort in descending order of total Amount
category_summary = category_summary.sort_values(by='Amount', ascending=False)

print("Aggregated and Sorted by Amount (Descending):")
category_summary=pd.DataFrame(category_summary)
print(category_summary)

Aggregated and Sorted by Amount (Descending):
      Category  Amount  Quantity
2  Electronics     550         2
1     Clothing     235         5
0        Books      65         8