In [2]:
import pandas as pd
import numpy as np

In [1]:
def analyze_text(sentence: str) -> dict:
    vowels = "aeiou"
    sentence = sentence.lower()
    vowel_count = sum(1 for char in sentence if char in vowels)
    consonant_count = sum(1 for char in sentence if char.isalpha() and char not in vowels)
    word_count = len(sentence.split())
    sentence_length = len(sentence)
    digit_count = sum(1 for char in sentence if char.isdigit())
    special_char_count = sum(1 for char in sentence if not char.isalnum() and not char.isspace())
    return {
        "vowel_count": vowel_count,
        "consonant_count": consonant_count,
        "word_count": word_count,
        "sentence_length": sentence_length,
        "digit_count": digit_count,
        "special_char_count": special_char_count
    }

In [12]:
sum([i for i in range(1,11) if i %2 == 0])

30

In [10]:
{i: ("Even" if i % 2 == 0 else "Odd") for i in range(1, 11)}

{1: 'Odd',
 2: 'Even',
 3: 'Odd',
 4: 'Even',
 5: 'Odd',
 6: 'Even',
 7: 'Odd',
 8: 'Even',
 9: 'Odd',
 10: 'Even'}

In [15]:
[i for i in "Hello World".lower() if i in "aeiou"]

['e', 'o', 'o']

In [2]:
text = "Data Science 101 @Ravi"
analyze_text(text)

{'vowel_count': 7,
 'consonant_count': 8,
 'word_count': 4,
 'sentence_length': 22,
 'digit_count': 3,
 'special_char_count': 1}

In [16]:
words = ["Data", "Science", "AI"]
{word: len(word) for word in words}

{'Data': 4, 'Science': 7, 'AI': 2}

In [23]:
{i : "Ravi Avaiya".lower().count(i) for i in "aeiou" if i in "Ravi Avaiya".lower()}

{'a': 4, 'i': 2}

In [28]:
palindrome = lambda x: True if x == x[::-1] else False
palindrome("madam"), palindrome("hello")

(True, False)

In [3]:
# Create a DataFrame with duplicate and missing values
data = {
    'ID': [1, 2, 3, 4, 5, 5, 6, None],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Eve', None, 'Grace'],
    'Age': [25, 30, 35, None, 40, 40, 45, 50],
    'Gender': ['F', 'M', 'M', 'M', 'F', 'F', None, 'F']
}

data = pd.DataFrame(data)
print(data)

    ID     Name   Age Gender
0  1.0    Alice  25.0      F
1  2.0      Bob  30.0      M
2  3.0  Charlie  35.0      M
3  4.0    David   NaN      M
4  5.0      Eve  40.0      F
5  5.0      Eve  40.0      F
6  6.0     None  45.0   None
7  NaN    Grace  50.0      F

In [4]:
data.dropna(inplace=True)  # Drop rows with any missing values
print("\nData after dropping rows with missing values:")
print(data)

Data after dropping rows with missing values:
    ID     Name   Age Gender
0  1.0    Alice  25.0      F
1  2.0      Bob  30.0      M
2  3.0  Charlie  35.0      M
4  5.0      Eve  40.0      F
5  5.0      Eve  40.0      F

In [18]:
data.groupby('Gender')['Age'].mean()

Gender
F    32.5
M    32.5
Name: Age, dtype: float64

In [20]:
print("\nData after sorting by Age in descending order:")
print(data.sort_values(by='Name', ascending=True))

Data after sorting by Age in descending order:
    ID     Name   Age Gender
0  1.0    Alice  25.0      F
1  2.0      Bob  30.0      M
2  3.0  Charlie  35.0      M
5  5.0      Eve  40.0      F

In [15]:
data.drop_duplicates(subset=['ID'], keep='first', inplace=True)  # Drop duplicate IDs, keeping the first occurrence

In [16]:
data

    ID     Name   Age Gender
5  5.0      Eve  40.0      F
2  3.0  Charlie  35.0      M
1  2.0      Bob  30.0      M
0  1.0    Alice  25.0      F

In [23]:
data.groupby('Gender')['Age'].agg(['count', 'mean', 'min', 'max'])

        count  mean   min   max
Gender
F           2  32.5  25.0  40.0
M           2  32.5  30.0  35.0

In [28]:
import pandas as pd

data = {
    'Department': ['Sales', 'Sales', 'HR', 'HR', 'IT', 'IT'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Salary': [50000, 55000, 60000, 62000, 70000, 72000],
    'Bonus': [5000, 7000, 6000, 6500, 8000, 8500]
}

df = pd.DataFrame(data)
df

  Department Employee  Salary  Bonus
0      Sales    Alice   50000   5000
1      Sales      Bob   55000   7000
2         HR  Charlie   60000   6000
3         HR    David   62000   6500
4         IT      Eve   70000   8000
5         IT    Frank   72000   8500

In [26]:
df.groupby(['Department','Employee']).agg({'Salary': 'sum', 'Bonus': 'mean'}).reset_index()

  Department Employee  Salary   Bonus
0         HR  Charlie   60000  6000.0
1         HR    David   62000  6500.0
2         IT      Eve   70000  8000.0
3         IT    Frank   72000  8500.0
4      Sales    Alice   50000  5000.0
5      Sales      Bob   55000  7000.0

In [29]:
df.groupby('Department').agg({'Salary': ['mean', 'max'], 'Bonus': ['sum', 'mean']}).reset_index()

  Department   Salary         Bonus
                 mean    max    sum    mean
0         HR  61000.0  62000  12500  6250.0
1         IT  71000.0  72000  16500  8250.0
2      Sales  52500.0  55000  12000  6000.0

In [30]:
df.groupby('Department').agg({'Salary': ['mean', 'max'], 'Bonus': ['sum', 'mean']})

             Salary         Bonus
               mean    max    sum    mean
Department
HR          61000.0  62000  12500  6250.0
IT          71000.0  72000  16500  8250.0
Sales       52500.0  55000  12000  6000.0

In [31]:
df.groupby('Department').size()

Department
HR       2
IT       2
Sales    2
dtype: int64

In [33]:
df.groupby('Department').count()

            Employee  Salary  Bonus
Department
HR                 2       2      2
IT                 2       2      2
Sales              2       2      2

In [35]:
df.groupby('Department')['Salary'].sum()

Department
HR       122000
IT       142000
Sales    105000
Name: Salary, dtype: int64

In [37]:
df.groupby('Department')['Salary'].sum().sort_values(ascending=True)

Department
Sales    105000
HR       122000
IT       142000
Name: Salary, dtype: int64

In [38]:
df.groupby(['Department', 'Employee'])['Salary'].sum().unstack()

Employee      Alice      Bob  Charlie    David      Eve    Frank
Department
HR              NaN      NaN  60000.0  62000.0      NaN      NaN
IT              NaN      NaN      NaN      NaN  70000.0  72000.0
Sales       50000.0  55000.0      NaN      NaN      NaN      NaN

In [41]:
df['Rating'] = pd.Categorical([3, 2, 3, 4, 1, 5], categories=[1, 2, 3, 4, 5], ordered=True)
df.groupby('Rating')['Salary'].sum()

C:\Users\ravia\AppData\Local\Temp\ipykernel_10180\3264575054.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Rating')['Salary'].sum()

Rating
1     70000
2     55000
3    110000
4     62000
5     72000
Name: Salary, dtype: int64